version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=ipo_platform
      - DB_USER=postgres
      - DB_PASSWORD=password
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRES_IN=24h
      - PORT=5000
      - UPLOAD_PATH=./uploads
      - MAX_FILE_SIZE=10485760
      - ADMIN_EMAIL=admin@ipo-platform.com
      - ADMIN_PASSWORD=admin123
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=ipo_platform
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: